-- MySQL Script generated by MySQL Workbench
-- Sat Nov 23 16:38:20 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema publicare
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema publicare
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `publicare` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `publicare` ;

-- -----------------------------------------------------
-- Table `publicare`.`classe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `publicare`.`classe` (
  `cod_classe` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `prefixo` VARCHAR(50) NOT NULL,
  `descricao` VARCHAR(255) NULL,
  `temfilhos` SMALLINT NOT NULL DEFAULT 0,
  `sistema` SMALLINT NOT NULL DEFAULT 0,
  `indexar` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_classe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `publicare`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `publicare`.`status` (
  `cod_status` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`cod_status`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `publicare`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `publicare`.`usuario` (
  `cod_usuario` INT NOT NULL AUTO_INCREMENT,
  `secao` VARCHAR(255) NULL,
  `nome` VARCHAR(255) NULL,
  `login` VARCHAR(50) NULL,
  `email` VARCHAR(255) NULL,
  `ramal` VARCHAR(50) NULL,
  `senha` VARCHAR(50) NULL,
  `chefia` INT NULL,
  `valido` SMALLINT NULL,
  `data_atualizacao` BIGINT NULL,
  `altera_senha` SMALLINT NULL,
  `ldap` SMALLINT NULL,
  PRIMARY KEY (`cod_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `publicare`.`pele`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `publicare`.`pele` (
  `cod_pele` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `prefixo` VARCHAR(50) NULL,
  `publica` SMALLINT NULL,
  PRIMARY KEY (`cod_pele`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `publicare`.`objeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `publicare`.`objeto` (
  `cod_objeto` INT NOT NULL AUTO_INCREMENT,
  `cod_pai` INT NULL,
  `cod_classe` INT NOT NULL,
  `cod_usuario` INT NOT NULL,
  `cod_pele` INT NULL,
  `cod_status` INT NOT NULL,
  `titulo` VARCHAR(255) NOT NULL,
  `descricao` TEXT NULL,
  `data_publicacao` BIGINT NOT NULL,
  `data_validade` BIGINT NOT NULL,
  `script_exibir` VARCHAR(255) NULL,
  `apagado` SMALLINT NOT NULL DEFAULT 1,
  `peso` INT NOT NULL DEFAULT 0,
  `data_exclusao` BIGINT NULL,
  `url_amigavel` VARCHAR(255) NULL,
  `versao` INT NOT NULL,
  `versao_publicada` INT NULL,
  PRIMARY KEY (`cod_objeto`),
  CONSTRAINT `fk_objeto_classe`
    FOREIGN KEY (`cod_classe`)
    REFERENCES `publicare`.`classe` (`cod_classe`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_objeto_status`
    FOREIGN KEY (`cod_status`)
    REFERENCES `publicare`.`status` (`cod_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_objeto_usuario`
    FOREIGN KEY (`cod_usuario`)
    REFERENCES `publicare`.`usuario` (`cod_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_objeto_pele`
    FOREIGN KEY (`cod_pele`)
    REFERENCES `publicare`.`pele` (`cod_pele`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_objeto_classe_idx` ON `publicare`.`objeto` (`cod_classe` ASC) VISIBLE;

CREATE INDEX `fk_objeto_status_idx` ON `publicare`.`objeto` (`cod_status` ASC) VISIBLE;

CREATE INDEX `fk_objeto_usuario_idx` ON `publicare`.`objeto` (`cod_usuario` ASC) VISIBLE;

CREATE INDEX `fk_objeto_pele_idx` ON `publicare`.`objeto` (`cod_pele` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `publicare`.`classexfilhos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `publicare`.`classexfilhos` (
  `cod_classe` INT NOT NULL,
  `cod_classe_filho` INT NOT NULL,
  PRIMARY KEY (`cod_classe`, `cod_classe_filho`),
  CONSTRAINT `fk_classexfilhos_classe`
    FOREIGN KEY (`cod_classe`)
    REFERENCES `publicare`.`classe` (`cod_classe`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_classexfilhos_classe_filho`
    FOREIGN KEY (`cod_classe_filho`)
    REFERENCES `publicare`.`classe` (`cod_classe`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_classexfilhos_classe_filho_idx` ON `publicare`.`classexfilhos` (`cod_classe_filho` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `publicare`.`tipodado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `publicare`.`tipodado` (
  `cod_tipodado` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `tabela` VARCHAR(50) NOT NULL,
  `delimitador` VARCHAR(1) NULL,
  PRIMARY KEY (`cod_tipodado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `publicare`.`propriedade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `publicare`.`propriedade` (
  `cod_propriedade` INT NOT NULL AUTO_INCREMENT,
  `cod_classe` INT NOT NULL,
  `cod_tipodado` INT NOT NULL,
  `cod_referencia_classe` INT NULL,
  `campo_ref` VARCHAR(50) NULL,
  `nome` VARCHAR(50) NULL,
  `posicao` INT NULL,
  `descricao` VARCHAR(255) NULL,
  `rotulo` VARCHAR(50) NULL,
  `rot1booleano` VARCHAR(50) NULL,
  `rot2booleano` VARCHAR(50) NULL,
  `obrigatorio` SMALLINT NULL,
  `seguranca` INT NULL,
  `valorpadrao` VARCHAR(255) NULL,
  PRIMARY KEY (`cod_propriedade`),
  CONSTRAINT `fk_propriedade_classe`
    FOREIGN KEY (`cod_classe`)
    REFERENCES `publicare`.`classe` (`cod_classe`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_propriedade_tipodado`
    FOREIGN KEY (`cod_tipodado`)
    REFERENCES `publicare`.`tipodado` (`cod_tipodado`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_propriedade_classe_idx` ON `publicare`.`propriedade` (`cod_classe` ASC) VISIBLE;

CREATE INDEX `fk_propriedade_tipodado_idx` ON `publicare`.`propriedade` (`cod_tipodado` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `publicare`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `publicare`.`tag` (
  `cod_tag` INT NOT NULL AUTO_INCREMENT,
  `nome_tag` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`cod_tag`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `publicare`.`tagxobjeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `publicare`.`tagxobjeto` (
  `cod_tagxobjeto` INT NOT NULL AUTO_INCREMENT,
  `cod_tag` INT NOT NULL,
  `cod_objeto` INT NOT NULL,
  PRIMARY KEY (`cod_tagxobjeto`),
  CONSTRAINT `fk_tagxobjeto_tag`
    FOREIGN KEY (`cod_tag`)
    REFERENCES `publicare`.`tag` (`cod_tag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tagxobjeto_objeto`
    FOREIGN KEY (`cod_objeto`)
    REFERENCES `publicare`.`objeto` (`cod_objeto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_tagxobjeto_tag_idx` ON `publicare`.`tagxobjeto` (`cod_tag` ASC) VISIBLE;

CREATE INDEX `fk_tagxobjeto_objeto_idx` ON `publicare`.`tagxobjeto` (`cod_objeto` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `publicare`.`tbl_blob`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `publicare`.`tbl_blob` (
  `cod_blob` INT NOT NULL AUTO_INCREMENT,
  `cod_obeto` INT NOT NULL,
  `cod_propriedade` INT NOT NULL,
  `arquivo` VARCHAR(255) NOT NULL,
  `tamanho` BIGINT NOT NULL,
  PRIMARY KEY (`cod_blob`),
  CONSTRAINT `fk_blob_objeto`
    FOREIGN KEY (`cod_obeto`)
    REFERENCES `publicare`.`objeto` (`cod_objeto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_blob_propriedade`
    FOREIGN KEY (`cod_propriedade`)
    REFERENCES `publicare`.`propriedade` (`cod_propriedade`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_blob_objeto_idx` ON `publicare`.`tbl_blob` (`cod_obeto` ASC) VISIBLE;

CREATE INDEX `fk_blob_propriedade_idx` ON `publicare`.`tbl_blob` (`cod_propriedade` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `publicare`.`tbl_boolean`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `publicare`.`tbl_boolean` (
  `cod_boolean` INT NOT NULL AUTO_INCREMENT,
  `cod_objeto` INT NOT NULL,
  `cod_propriedade` INT NOT NULL,
  `valor` SMALLINT NULL,
  PRIMARY KEY (`cod_boolean`),
  CONSTRAINT `fk_boolean_objeto`
    FOREIGN KEY (`cod_objeto`)
    REFERENCES `publicare`.`objeto` (`cod_objeto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_boolean_propriedade`
    FOREIGN KEY (`cod_propriedade`)
    REFERENCES `publicare`.`propriedade` (`cod_propriedade`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_boolean_objeto_idx` ON `publicare`.`tbl_boolean` (`cod_objeto` ASC) VISIBLE;

CREATE INDEX `fk_boolean_propriedade_idx` ON `publicare`.`tbl_boolean` (`cod_propriedade` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `publicare`.`tbl_date`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `publicare`.`tbl_date` (
  `cod_date` INT NOT NULL AUTO_INCREMENT,
  `cod_objeto` INT NOT NULL,
  `cod_propriedade` INT NOT NULL,
  `valor` BIGINT NULL,
  PRIMARY KEY (`cod_date`),
  CONSTRAINT `fk_date_objeto`
    FOREIGN KEY (`cod_objeto`)
    REFERENCES `publicare`.`objeto` (`cod_objeto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_date_propriedade`
    FOREIGN KEY (`cod_propriedade`)
    REFERENCES `publicare`.`propriedade` (`cod_propriedade`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_date_objeto_idx` ON `publicare`.`tbl_date` (`cod_objeto` ASC) VISIBLE;

CREATE INDEX `fk_date_propriedade_idx` ON `publicare`.`tbl_date` (`cod_propriedade` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `publicare`.`tbl_float`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `publicare`.`tbl_float` (
  `cod_float` INT NOT NULL AUTO_INCREMENT,
  `cod_objeto` INT NOT NULL,
  `cod_propriedade` INT NOT NULL,
  `valor` DOUBLE NULL,
  PRIMARY KEY (`cod_float`),
  CONSTRAINT `fk_float_objeto`
    FOREIGN KEY (`cod_objeto`)
    REFERENCES `publicare`.`objeto` (`cod_objeto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_float_propriedade`
    FOREIGN KEY (`cod_propriedade`)
    REFERENCES `publicare`.`propriedade` (`cod_propriedade`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_float_objeto_idx` ON `publicare`.`tbl_float` (`cod_objeto` ASC) VISIBLE;

CREATE INDEX `fk_float_propriedade_idx` ON `publicare`.`tbl_float` (`cod_propriedade` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `publicare`.`tbl_integer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `publicare`.`tbl_integer` (
  `cod_integer` INT NOT NULL AUTO_INCREMENT,
  `cod_objeto` INT NOT NULL,
  `cod_propriedade` INT NOT NULL,
  `valor` INT NULL,
  PRIMARY KEY (`cod_integer`),
  CONSTRAINT `fk_integer_objeto`
    FOREIGN KEY (`cod_objeto`)
    REFERENCES `publicare`.`objeto` (`cod_objeto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_integer_propriedade`
    FOREIGN KEY (`cod_propriedade`)
    REFERENCES `publicare`.`propriedade` (`cod_propriedade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_integer_objeto_idx` ON `publicare`.`tbl_integer` (`cod_objeto` ASC) VISIBLE;

CREATE INDEX `fk_integer_propriedade_idx` ON `publicare`.`tbl_integer` (`cod_propriedade` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `publicare`.`tbl_objref`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `publicare`.`tbl_objref` (
  `cod_objref` INT NOT NULL AUTO_INCREMENT,
  `cod_objeto` INT NOT NULL,
  `cod_propriedade` INT NOT NULL,
  `valor` INT NULL,
  PRIMARY KEY (`cod_objref`),
  CONSTRAINT `fk_objref_objeto`
    FOREIGN KEY (`cod_objeto`)
    REFERENCES `publicare`.`objeto` (`cod_objeto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_objref_propriedade`
    FOREIGN KEY (`cod_propriedade`)
    REFERENCES `publicare`.`propriedade` (`cod_propriedade`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_objref_objeto_idx` ON `publicare`.`tbl_objref` (`cod_objeto` ASC) VISIBLE;

CREATE INDEX `fk_objref_propriedade_idx` ON `publicare`.`tbl_objref` (`cod_propriedade` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `publicare`.`tbl_string`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `publicare`.`tbl_string` (
  `cod_string` INT NOT NULL AUTO_INCREMENT,
  `cod_objeto` INT NOT NULL,
  `cod_propriedade` INT NOT NULL,
  `valor` VARCHAR(1000) NULL,
  PRIMARY KEY (`cod_string`),
  CONSTRAINT `fk_string_objeto`
    FOREIGN KEY (`cod_objeto`)
    REFERENCES `publicare`.`objeto` (`cod_objeto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_string_propriedade`
    FOREIGN KEY (`cod_propriedade`)
    REFERENCES `publicare`.`propriedade` (`cod_propriedade`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_string_objeto_idx` ON `publicare`.`tbl_string` (`cod_objeto` ASC) VISIBLE;

CREATE INDEX `fk_string_propriedade_idx` ON `publicare`.`tbl_string` (`cod_propriedade` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `publicare`.`tbl_text`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `publicare`.`tbl_text` (
  `cod_text` INT NOT NULL AUTO_INCREMENT,
  `cod_objeto` INT NOT NULL,
  `cod_propriedade` INT NOT NULL,
  `valor` TEXT NULL,
  PRIMARY KEY (`cod_text`),
  CONSTRAINT `fk_text_objeto`
    FOREIGN KEY (`cod_objeto`)
    REFERENCES `publicare`.`objeto` (`cod_objeto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_text_propriedaed`
    FOREIGN KEY (`cod_propriedade`)
    REFERENCES `publicare`.`propriedade` (`cod_propriedade`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_text_objeto_idx` ON `publicare`.`tbl_text` (`cod_objeto` ASC) VISIBLE;

CREATE INDEX `fk_text_propriedaed_idx` ON `publicare`.`tbl_text` (`cod_propriedade` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `publicare`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `publicare`.`perfil` (
  `cod_perfil` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`cod_perfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `publicare`.`objetoxusuarioxperfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `publicare`.`objetoxusuarioxperfil` (
  `cod_usuario` INT NOT NULL,
  `cod_objeto` INT NOT NULL,
  `cod_perfil` INT NOT NULL,
  PRIMARY KEY (`cod_usuario`, `cod_objeto`, `cod_perfil`),
  CONSTRAINT `fk_objetoxusuarioxperfil_objeto`
    FOREIGN KEY (`cod_objeto`)
    REFERENCES `publicare`.`objeto` (`cod_objeto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_objetoxusuarioxperfil_usuario`
    FOREIGN KEY (`cod_usuario`)
    REFERENCES `publicare`.`usuario` (`cod_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_objetoxusuarioxperfil_perfil`
    FOREIGN KEY (`cod_perfil`)
    REFERENCES `publicare`.`perfil` (`cod_perfil`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_objetoxusuarioxperfil_objeto_idx` ON `publicare`.`objetoxusuarioxperfil` (`cod_objeto` ASC) VISIBLE;

CREATE INDEX `fk_objetoxusuarioxperfil_perfil_idx` ON `publicare`.`objetoxusuarioxperfil` (`cod_perfil` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `publicare`.`pilha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `publicare`.`pilha` (
  `cod_pilha` INT NOT NULL AUTO_INCREMENT,
  `cod_objeto` INT NOT NULL,
  `cod_usuario` INT NOT NULL,
  `cod_tipo` INT NULL,
  `datahora` BIGINT NULL,
  PRIMARY KEY (`cod_pilha`),
  CONSTRAINT `fk_pilha_objeto`
    FOREIGN KEY (`cod_objeto`)
    REFERENCES `publicare`.`objeto` (`cod_objeto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pilha_usuario`
    FOREIGN KEY (`cod_usuario`)
    REFERENCES `publicare`.`usuario` (`cod_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_pilha_objeto_idx` ON `publicare`.`pilha` (`cod_objeto` ASC) VISIBLE;

CREATE INDEX `fk_pilha_usuario_idx` ON `publicare`.`pilha` (`cod_usuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `publicare`.`classexobjeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `publicare`.`classexobjeto` (
  `cod_classe` INT NOT NULL,
  `cod_objeto` INT NOT NULL,
  PRIMARY KEY (`cod_classe`, `cod_objeto`),
  CONSTRAINT `fk_classexobjeto_classe`
    FOREIGN KEY (`cod_classe`)
    REFERENCES `publicare`.`classe` (`cod_classe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_classexobjeto_objeto`
    FOREIGN KEY (`cod_objeto`)
    REFERENCES `publicare`.`objeto` (`cod_objeto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_classexobjeto_objeto_idx` ON `publicare`.`classexobjeto` (`cod_objeto` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `publicare`.`infoperfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `publicare`.`infoperfil` (
  `cod_infoperfil` INT NOT NULL AUTO_INCREMENT,
  `cod_perfil` INT NOT NULL,
  `acao` VARCHAR(255) NULL,
  `script` VARCHAR(255) NULL,
  `donooupublicado` SMALLINT NULL,
  `sopublicado` SMALLINT NULL,
  `sodono` SMALLINT NULL,
  `naomenu` SMALLINT NULL,
  `ordem` INT NULL,
  `icone` VARCHAR(50) NULL,
  PRIMARY KEY (`cod_infoperfil`),
  CONSTRAINT `fk_infoperfil_perfil`
    FOREIGN KEY (`cod_perfil`)
    REFERENCES `publicare`.`perfil` (`cod_perfil`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_infoperfil_perfil_idx` ON `publicare`.`infoperfil` (`cod_perfil` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `publicare`.`logobjeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `publicare`.`logobjeto` (
  `cod_logobjeto` INT NOT NULL AUTO_INCREMENT,
  `cod_objeto` INT NOT NULL,
  `cod_usuario` INT NOT NULL,
  `estampa` BIGINT NOT NULL,
  `cod_operacao` INT NULL,
  `cod_status` INT NULL,
  `mensagem` VARCHAR(255) NULL,
  `ip` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_logobjeto`),
  CONSTRAINT `fk_logobjeto_objeto`
    FOREIGN KEY (`cod_objeto`)
    REFERENCES `publicare`.`objeto` (`cod_objeto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_logobjeto_usuario`
    FOREIGN KEY (`cod_usuario`)
    REFERENCES `publicare`.`usuario` (`cod_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_logobjeto_status`
    FOREIGN KEY (`cod_status`)
    REFERENCES `publicare`.`status` (`cod_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_logobjeto_objeto_idx` ON `publicare`.`logobjeto` (`cod_objeto` ASC) VISIBLE;

CREATE INDEX `fk_logobjeto_usuario_idx` ON `publicare`.`logobjeto` (`cod_usuario` ASC) VISIBLE;

CREATE INDEX `fk_logobjeto_status_idx` ON `publicare`.`logobjeto` (`cod_status` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `publicare`.`parentesco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `publicare`.`parentesco` (
  `cod_objeto` INT NOT NULL,
  `cod_pai` INT NOT NULL,
  `ordem` INT NOT NULL,
  PRIMARY KEY (`cod_objeto`, `cod_pai`, `ordem`),
  CONSTRAINT `fk_parentesco_objeto`
    FOREIGN KEY (`cod_objeto`)
    REFERENCES `publicare`.`objeto` (`cod_objeto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_parentesco_objeto_pai`
    FOREIGN KEY (`cod_pai`)
    REFERENCES `publicare`.`objeto` (`cod_objeto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_parentesco_objeto_pai_idx` ON `publicare`.`parentesco` (`cod_pai` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `publicare`.`pendencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `publicare`.`pendencia` (
  `cod_pendencia` INT NOT NULL AUTO_INCREMENT,
  `cod_usuario` INT NOT NULL,
  `cod_objeto` INT NOT NULL,
  PRIMARY KEY (`cod_pendencia`),
  CONSTRAINT `fk_pendencia_objeto`
    FOREIGN KEY (`cod_objeto`)
    REFERENCES `publicare`.`objeto` (`cod_objeto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pendencia_usuario`
    FOREIGN KEY (`cod_usuario`)
    REFERENCES `publicare`.`usuario` (`cod_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_pendencia_objeto_idx` ON `publicare`.`pendencia` (`cod_objeto` ASC) VISIBLE;

CREATE INDEX `fk_pendencia_usuario_idx` ON `publicare`.`pendencia` (`cod_usuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `publicare`.`usuarioxobjetoxperfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `publicare`.`usuarioxobjetoxperfil` (
  `cod_usuario` INT NOT NULL,
  `cod_objeto` INT NOT NULL,
  `cod_perfil` INT NOT NULL,
  PRIMARY KEY (`cod_usuario`, `cod_objeto`, `cod_perfil`),
  CONSTRAINT `fk_usuarioxobjetoxperfil_usuario`
    FOREIGN KEY (`cod_usuario`)
    REFERENCES `publicare`.`usuario` (`cod_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_usuarioxobjetoxperfil_objeto`
    FOREIGN KEY (`cod_objeto`)
    REFERENCES `publicare`.`objeto` (`cod_objeto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_usuarioxobjetoxperfil_perfil`
    FOREIGN KEY (`cod_perfil`)
    REFERENCES `publicare`.`perfil` (`cod_perfil`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_usuarioxobjetoxperfil_objeto_idx` ON `publicare`.`usuarioxobjetoxperfil` (`cod_objeto` ASC) VISIBLE;

CREATE INDEX `fk_usuarioxobjetoxperfil_perfil_idx` ON `publicare`.`usuarioxobjetoxperfil` (`cod_perfil` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `publicare`.`versaoobjeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `publicare`.`versaoobjeto` (
  `cod_versaoobjeto` INT NOT NULL AUTO_INCREMENT,
  `cod_objeto` INT NOT NULL,
  `versao` INT NOT NULL,
  `conteudo` TEXT NULL,
  `data_criacao` DATETIME NULL,
  `cod_usuario` INT NULL,
  `ip` VARCHAR(30) NULL,
  PRIMARY KEY (`cod_versaoobjeto`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `publicare`.`status`
-- -----------------------------------------------------
START TRANSACTION;
USE `publicare`;
INSERT INTO `publicare`.`status` (`cod_status`, `nome`) VALUES (1, 'Privado');
INSERT INTO `publicare`.`status` (`cod_status`, `nome`) VALUES (2, 'Publicado');
INSERT INTO `publicare`.`status` (`cod_status`, `nome`) VALUES (3, 'Rejeitado');
INSERT INTO `publicare`.`status` (`cod_status`, `nome`) VALUES (4, 'Submetido');

COMMIT;

